services:
  postgres:
    image: postgres:14
    container_name: ${CLASS_SERVICE_CONTAINER_NAME:-fitness-class-db}
    environment:
      POSTGRES_USER: ${DB_USER:-fitness_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${CLASS_SERVICE_DB_NAME:-fitness_class_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${CLASS_SERVICE_DB_PORT:-5436}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - ${DOCKER_NETWORK_NAME:-fitness-network}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-fitness_user} -d ${CLASS_SERVICE_DB_NAME:-fitness_class_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  class-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness-class-service
    env_file:
      - .env.docker
    environment:
      DB_HOST: postgres
      DB_PORT: 5432  # Use PostgreSQL's internal port (5432) for Docker networking
      DB_USER: ${DB_USER:-fitness_user}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      CLASS_SERVICE_DB_NAME: ${CLASS_SERVICE_DB_NAME:-fitness_class_db}
      CLASS_SERVICE_PORT: ${CLASS_SERVICE_PORT:-8005}
      CLASS_SERVICE_HOST: ${CLASS_SERVICE_HOST:-0.0.0.0}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    ports:
      - "${CLASS_SERVICE_PORT:-8005}:8005"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ${DOCKER_NETWORK_NAME:-fitness-network}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8005/health"]
      interval: 180s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  fitness-network:
    external: true
    name: ${DOCKER_NETWORK_NAME:-fitness-network}

volumes:
  postgres_data:
    driver: local
