server:
  port: 8000
  readTimeout: 15s
  writeTimeout: 15s
  idleTimeout: 60s

services:
  member:
    url: http://localhost:8001
    timeout: 10s
  staff:
    url: http://localhost:8002
    timeout: 10s
  class:
    url: http://localhost:8003
    timeout: 10s
  facility:
    url: http://localhost:8004
    timeout: 10s
  payment:
    url: http://localhost:8005
    timeout: 10s